= Juego de Sakura - 2021

Giannina Perez 43.729.769/2020 <giannina-b-perez@hotmail.com>
v1, {docdate}. Docentes: Hernán Rondelli y Leonardo Waingarten (COM-01)

:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

== Introducción

El objetivo de mi primer proyecto fue desarrollar un videojuego con programación orientada a objetos. Este se construyó a partir de un `entorno.jar` en Java. El videojuego consiste en controlar a Sakura, quien debe entregar pedidos de una florería en las casas de su aldea. Su trabajo se complica al tener ninjas enemigos rondando por la zona, por lo cual Sakura deberá esquivarlos para no ser atacada. Su rasengan le permite matar ninjas para liberar la zona, pero estos reaparecen al entregar un pedido.

== Descripción

*Decisiones y diseños*

Método `salioDeCalle()`: Al tener la aldea medida por calles y no por manzanas, decidimos comprobar si Sakura salía de las calles estableciendo manualmente los límites regidos por dichas calles, teniendo en cuenta la medida del entorno.

`Juego.java`: Contiene el código principal.

- *Métodos de la clase Sakura*
   
 * `mirarIzquierda()`: La dirección de Sakura se establece en Math.PI.
 
 * `mirarDerecha()`: La dirección de Sakura se establece en 0.

 * `mirarArriba()`: La dirección de Sakura se establece en - Math.PI / 2.
 
 * `mirarAbajo()`: La dirección de Sakura se establece en Math.PI / 2.

 * `dibujar()`: Dibuja a Sakura en el entorno, dependiendo de la dirección en la que se encuentre se va a dibujar de distinta manera.

 * `mover()`: Sakura se mueve en el entorno hacia la dirección elegida.

 * `colisionoConElEntorno()`: Este boolean devuelve true si Sakura choca con los bordes del entorno.

 * `colisionoConNinja()`: Este boolean devuelve true si Sakura choca con un ninja.

 * `llegoACasaDelPedido()`: Este boolean devuelve `true` si Sakura pasa por en frente de la casa donde tiene que llevar el pedido.

 * `salioDeCalle()`: El método verifica si Sakura se intenta mover por
 fuera de las calles, si es así devuelve true. Esta compuesto por dos
 partes, una verifica si sale de las calles verticales, es decir por
 los costados. Y la otra verifica si sale de las calles horizontales,
 es decir por arriba o abajo de las calles. En cada caso, se verifica también que no esté en una intersección entre calles, ya que en ese caso sí podría avanzar y moverse.

 * `noAvanzar()`: Limita el movimiento de Sakura dependiendo de si está saliendo por los bordes del entorno o si está saliendo de las calles.

 * `correr()`: La velocidad de Sakura se establece en 4.

 * `caminar()`: La velocidad de Sakura se establece en 2.

 * `lanzarRasengan()`: Crea y retorna un rasengan que va hacia la última dirección en la que se movió Sakura.

 - *Métodos de la clase Ninja*
   
 * `dibujar()`: Dibuja a un ninja en el entorno, dependiendo de la dirección en la que se encuentre se va a dibujar de distinta manera.

 * `mover()`: El ninja se mueve en el entorno siempre en la misma dirección. Si choca contra los bordes del entorno, reaparece del lado contrario.

 * `getDireccion()`: Se utiliza en la clase Juego, para la reaparición de los ninjas.

 * `getX()`: Se utiliza en los métodos `colisionoConNinja` en la clase Sakura y en la clase Rasengan.

 * `getY()`: Se utiliza en los métodos `colisionoConNinja` en la clase Sakura y en la clase Rasengan.

 - *Métodos de la clase Casa*
   
 * `dibujar()`: Dibuja una casa roja o una casa azul en el entorno, dependiendo de su número.

 * `marcar()`: Dibuja una flecha encima de la casa elegida. En las casas que están en el borde superior de la pantalla la flecha que marca la casa se dibuja desde abajo para que no salga de la pantalla.

 * `getX()`: Se utiliza en el método `llegoACasaDelPedido` en la clase Sakura.

 * `getY()`: Se utiliza en el método `llegoACasaDelPedido` en la clase Sakura.

 - *Método de la clase Calle*
   
 * `dibujar()`: Dibuja un rectángulo en el entorno, representando una calle.

 - *Métodos de la clase Rasengan*
   
 * `dibujar()`: Dibuja el rasengan en el entorno.

 * `mover()`: El rasengan se mueve en el entorno hacia la dirección elegida.

 * `colisionoConElEntorno()`: Este boolean devuelve true si el rasengan choca con los bordes del entorno.
 
 * `colisionoConLaCiudad()`: Este boolean devuelve true si el rasengan se sale de las calles.
 
 * `colisionoConNinja()`: Este boolean devuelve true si el rasengan choca con un ninja.
